# Generated by Django 2.2.1 on 2019-07-27 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samari', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='attending',
            field=models.CharField(default='Yes', max_length=256),
        ),
    ]
