# Generated by Django 2.2.4 on 2019-09-25 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('samari', '0002_rsvp_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
