# Generated by Django 2.2.4 on 2019-10-21 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samari', '0003_rsvp_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rsvp',
            name='attending',
            field=models.CharField(default='Both', max_length=256),
        ),
    ]
